name: sub

on:
  workflow_dispatch:

permissions:
  statuses: write

concurrency:
  # limit concurrency to 1
  group: ${{ github.workflow }}

jobs:
  job:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: self-hosted
    steps:
      - name: sub routine
        id: sub_routine
        continue-on-error: true
        run: |
          echo "success"
          # echo "failure"
          # exit 1
      - name: update status
        run: |
          # latest run id of sub.yaml
          latest_sub_run_id=$(gh api repos/rokkish/sync_status_check/actions/workflows/sub.yaml/runs | jq -r '.workflow_runs[0].id')

          # latest run commit hash of main.yaml
          latest_main_run_commit_hash=$(gh api repos/rokkish/sync_status_check/actions/workflows/main.yaml/runs | jq -r '.workflow_runs[0].head_sha')

          # latest run url of sub.yaml
          target_url=$(gh api repos/rokkish/sync_status_check/actions/runs/${latest_sub_run_id} | jq -r '.html_url')

          # get result of sub step
          # not ${{ steps.sub_routine.conclusion }}
          conclusion=${{ steps.sub_routine.outcome }}

          # update status
          if [[ "$conclusion" == "success" ]]; then
            sub_state="success"
          else
            sub_state="failure"
          fi
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            repos/rokkish/sync_status_check/statuses/${latest_main_run_commit_hash} \
            -f state=${sub_state} \
            -f target_url=${target_url} \
            -f description='called by main' \
            -f context='sub workflow'
